import assert from 'node:assert/strict';
import {DESIGN_LIBRARY,eligibleDesigns,artDirect,recentDesigns,rememberDesign} from '../assets/studio-art-direction.mjs';
let state=19;
const random=()=>{state=(state*1664525+1013904223)>>>0;return state/4294967296;};
const product={sourceUrl:'https://example.test/item',productName:'리브 티셔츠',category:'fashion-top',quantity:4,salePrice:79000,photos:[{personKind:'body'},{personKind:'body'}]};
const plans=Array.from({length:6},(_,id)=>({id,photo:0,photoSet:[0,1],copyBrief:'실제 상품',emphasis:'product'}));
assert.equal(DESIGN_LIBRARY.length,30);
assert.equal(new Set(DESIGN_LIBRARY.map(d=>d.id)).size,30);
const seen=new Set();
for(const category of ['fashion-top','beauty','food'])for(let n=0;n<200;n++){
 const result=artDirect(plans,{...product,category},{random});
 assert.equal(new Set(result.map(p=>p.designId)).size,6);
 assert.equal(result.filter(p=>p.fontFamily==='sans').length,4);
 assert.ok(new Set(result.map(p=>p.designFamily)).size>=3);
 result.forEach(p=>{seen.add(p.designId);assert.ok(p.artDirection.includes('supplied scene'));assert.equal(p.completeBanner,true);});
}
assert.equal(seen.size,30,'Every library design can actually be selected');
const sparse={category:'food',photos:[{personKind:'none'}]};
assert.ok(eligibleDesigns({photo:0},sparse).every(d=>!d.requires));
assert.equal(artDirect(plans.map(p=>({...p,photoSet:null})),sparse,{random}).length,6);
assert.ok(!eligibleDesigns({...plans[0],scene:'product only',keep:'product'},product).some(d=>d.id==='runway'));
const recent=['editorial','margin','fullbleed','vertical','quiet','portrait'];
assert.ok(artDirect(plans,product,{random,recent}).every(p=>!recent.includes(p.designId)));
const memory=new Map(),storage={getItem:k=>memory.get(k),setItem:(k,v)=>memory.set(k,v)};
for(const d of DESIGN_LIBRARY)rememberDesign(product,d.id,storage);
assert.equal(recentDesigns(product,storage).length,12);
assert.deepEqual(recentDesigns({...product,productName:'other'},storage),[]);
const broken={getItem:()=>{throw Error('blocked');},setItem:()=>{throw Error('blocked');}};
assert.deepEqual(recentDesigns(product,broken),[]);
assert.doesNotThrow(()=>rememberDesign(product,'editorial',broken));
console.log('PASS: 30 reachable designs; 600 selections; eligibility, 4:2 fonts, diversity, recent history and blocked storage');
