// Reference images (competitor ads + NHN's own produced materials),
// grouped by industry category, for the "이미지 레퍼런스" board. Team members
// find competitor ads on Google Ads Transparency Center / Meta Ad Library
// themselves, then send the screenshots to Claude to add here — this is a
// curated library, not a live search of those external sites (neither has
// an accessible API we can call from this app).
//
// HOW TO ADD A REFERENCE IMAGE:
// Send Claude the image and say which category and brand it's for, or name
// files like {카테고리}_{브랜드코드}_{번호}.jpg (e.g. 금융_DB_01.jpg) and send
// several at once — Claude will run scripts/bulk_add_reference_images.py,
// which resizes the image, uploads it to Vercel Blob Storage, and inserts
// the entry here automatically.
//
// If the image is a material NHN itself produced (not a competitor ad),
// add "NHN" as an extra underscore segment anywhere after the brand, e.g.
// 금융_하나카드_NHN_02.jpg — the import script marks it `ownWork: true`,
// which shows a small "NHN AD" badge on the card in the UI so team-made work
// is visually distinguishable from competitor references at a glance.
//
// Image bytes live in Vercel Blob Storage, not in this file — only the
// URLs are stored here, which is why this file stays small even as the
// library grows to hundreds of images. Each item has two versions:
// - thumbUrl: compressed thumbnail (700px, q74), used for the grid
// - fullUrl: higher quality version (2000px, q92), used in the lightbox
//   when someone clicks a thumbnail (only fetched then, not upfront)
//
// Structure:
// REFERENCE_CATEGORIES = {
//   '<url-safe-id>': {
//     name: '<드롭다운에 표시할 이름>',
//     items: [
//       { brandName: '<브랜드명>', note: '<한 줄 메모>', mimeType: 'image/jpeg', thumbUrl: '<Blob URL>', fullUrl: '<Blob URL>', ownWork: true | undefined },
//       ...
//     ],
//   },
// }
// ownWork는 NHN이 직접 제작한 소재일 때만 true로 채우고, 일반 경쟁사
// 레퍼런스는 그냥 생략하면 됩니다(생략 시 배지 없음).

export const REFERENCE_CATEGORIES = {
  'fashion': { name: "패션", items: [
      { brandName: "안다르", note: "시즌오프 맨즈 전상품 최대 80%", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/fashion/%EC%95%88%EB%8B%A4%EB%A5%B4-057-thumb-BX8fn8IYWDHihhrl1fCdpCTF1RGwEw.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/fashion/%EC%95%88%EB%8B%A4%EB%A5%B4-057-full-vf7VAtbj4C8j8wrhsyyzl17wIx0lKZ.jpg" },
      { brandName: "안다르", note: "데님 팬츠, 여행룩 콘셉트 컷", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/fashion/%EC%95%88%EB%8B%A4%EB%A5%B4-093-thumb-s5YhaxmZvV36gi9AvUzPxRWIrwCdvR.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/fashion/%EC%95%88%EB%8B%A4%EB%A5%B4-093-full-cfLPieTt2UNdQCnA3m2fnpipLXPYbL.jpg" },
      { brandName: "SSF SHOP", note: "키즈 컬렉션, 곰인형 소품 활용", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/fashion/ssf-shop-110-thumb-tPD9YiFEAdrnR7pLfWNgMQn4wjH8l4.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/fashion/ssf-shop-110-full-0gAV3DBfI3PCbB58LCFGZLr1bl85zW.jpg" },
      { brandName: "안다르", note: "11주년 앵콜특가, 행어 제품컷", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/fashion/%EC%95%88%EB%8B%A4%EB%A5%B4-111-thumb-KkCJsfEjsb9T7tBXxqx6zpupAFKc1a.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/fashion/%EC%95%88%EB%8B%A4%EB%A5%B4-111-full-xYKIzghKjXR8GgLaAmv49KEYf9FVak.jpg" },
      { brandName: "마리끌레르", note: "매장 실물 핏 화보형 비주얼", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/fashion/%EB%A7%88%EB%A6%AC%EB%81%8C%EB%A0%88%EB%A5%B4-118-thumb-twnTZXHaotbgVELvIQrMMOagjavde9.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/fashion/%EB%A7%88%EB%A6%AC%EB%81%8C%EB%A0%88%EB%A5%B4-118-full-munn2eoZfRnwqdNQg5LHC7sllfgJ3d.jpg" },
      { brandName: "MLB KIDS", note: "봄나들이 인싸룩, 폴라로이드 콘셉트", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/fashion/mlb-kids-125-thumb-6ttaWIXijZTxBaEQb5WWU1VBksqGBd.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/fashion/mlb-kids-125-full-QRvUUtC4TRXpf2nChSxY8j2iiQntzl.jpg" },
      { brandName: "MLB KIDS", note: "여름휴가 체크인 라이브 예고", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/fashion/mlb-kids-126-thumb-YBib5KyMmexCjkKySdTX6X5HlUNu0k.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/fashion/mlb-kids-126-full-znOr6qEbdMeFHNQyl2UgZB202GfYDH.jpg" },
      { brandName: "브룩스브라더스", note: "26SS 컬렉션 최대40%, 커플 화보", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/fashion/%EB%B8%8C%EB%A3%A9%EC%8A%A4%EB%B8%8C%EB%9D%BC%EB%8D%94%EC%8A%A4-130-thumb-GJCI1f9itmm8FGnhF8cZjiErnivmcX.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/fashion/%EB%B8%8C%EB%A3%A9%EC%8A%A4%EB%B8%8C%EB%9D%BC%EB%8D%94%EC%8A%A4-130-full-RlKudcDbmI4CgPzHw68qXRT5lCK5Jj.jpg" },
      { brandName: "POTTERY", note: "셔츠+타이 세트, 네이버 입점기념 25%", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/fashion/pottery-135-thumb-8J6sgrK8kx4QnldfymyNpdzbaGUqFr.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/fashion/pottery-135-full-9efdW6axXDUT5jwiOIeVXrBrQnwDaF.jpg" },
      { brandName: "메종키츠네(SSF SHOP)", note: "첫구매 한정, 여우 티셔츠 그림자 연출", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/fashion/%EB%A9%94%EC%A2%85%ED%82%A4%EC%B8%A0%EB%84%A4-ssf-shop-137-thumb-dHbpGEaKNnpFcsK8A1zpA4gKgKVVVS.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/fashion/%EB%A9%94%EC%A2%85%ED%82%A4%EC%B8%A0%EB%84%A4-ssf-shop-137-full-RkcxJ5K9aLYStwW1OUb3SnJNu14ar8.jpg" },
      { brandName: "현대HI", note: "24시간 한정 타임딜, 티셔츠 17% 쿠폰", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/fashion/nhnad-%ED%83%80%EC%9E%84%EB%94%9C-%EB%B8%8C%EB%9E%9C%EB%93%9C%EB%AA%85-%ED%99%95%EC%9D%B8-%ED%95%84%EC%9A%94-12-thumb-Y9NGAuyi4ATbPtULUcDCorVyNxKZ2c.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/fashion/nhnad-%ED%83%80%EC%9E%84%EB%94%9C-%EB%B8%8C%EB%9E%9C%EB%93%9C%EB%AA%85-%ED%99%95%EC%9D%B8-%ED%95%84%EC%9A%94-12-full-Fah2Pn4xGdnNdmh6ultQZkLWSo39Ss.jpg", ownWork: true },
    ] },
  'finance': { name: "금융", items: [
      { brandName: "삼성화재", note: "다이렉트 운전자보험, 캐릭터 일러스트로 친근함 강조", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/finance/%EC%82%BC%EC%84%B1%ED%99%94%EC%9E%AC-005-thumb-gRryaZ9eDYfPkvQQMFEHQUtXMHS39k.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/finance/%EC%82%BC%EC%84%B1%ED%99%94%EC%9E%AC-005-full-hVE2eIUxqEa2A0pynGvnERobXn0AYa.jpg" },
      { brandName: "삼성화재", note: "다이렉트 치아보험, 치아 캐릭터 일러스트", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/finance/%EC%82%BC%EC%84%B1%ED%99%94%EC%9E%AC-009-thumb-m4eaeVEtoxphcczLlHeEVPFlwGEVJ3.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/finance/%EC%82%BC%EC%84%B1%ED%99%94%EC%9E%AC-009-full-Coits9utCdnCcxrwDsrVNvrqON09vx.jpg" },
      { brandName: "삼성생명", note: "다이렉트 뇌심장질환보험, 통계수치 인용형", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/finance/%EC%82%BC%EC%84%B1%EC%83%9D%EB%AA%85-014-thumb-eRPlXTs0SVgWBBoaqWoRFVR23JR5vv.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/finance/%EC%82%BC%EC%84%B1%EC%83%9D%EB%AA%85-014-full-DbfE5LwDo2YKqDNO7tkPYS0opB9byz.jpg" },
      { brandName: "대신증권", note: "신규계좌 개설 이벤트, 금액 강조형", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/finance/%EB%8C%80%EC%8B%A0%EC%A6%9D%EA%B6%8C-017-thumb-35YasVdvjeeGW6QUgHHNsS2jPFl8b7.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/finance/%EB%8C%80%EC%8B%A0%EC%A6%9D%EA%B6%8C-017-full-pQzQ3R9MouJpgAF2q9LeAGEKASZefn.jpg" },
      { brandName: "삼성생명", note: "뇌심장질환보험, 비타민으로 은유한 카피", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/finance/%EC%82%BC%EC%84%B1%EC%83%9D%EB%AA%85-021-thumb-zp1gPvAeyY6wnXTVBClwae8rR0xb5g.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/finance/%EC%82%BC%EC%84%B1%EC%83%9D%EB%AA%85-021-full-yDYhAu6Vt9w9rxJDaqKmNBCrpgMlmC.jpg" },
      { brandName: "삼성생명", note: "뇌심장 대비 강조, 통계 인용형(변형)", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/finance/%EC%82%BC%EC%84%B1%EC%83%9D%EB%AA%85-024-thumb-1cGtb9WzcaXaqWJXjNRhuPmHmIqEii.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/finance/%EC%82%BC%EC%84%B1%EC%83%9D%EB%AA%85-024-full-AWGteyoZkBwYUtlcH8MCo2RUEFLKbD.jpg" },
      { brandName: "삼성화재", note: "펫보험 vs 펫적금 비교형 카피", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/finance/%EC%82%BC%EC%84%B1%ED%99%94%EC%9E%AC-028-thumb-g3qselXBJ0EJNeyMyX8ZnM9fEDpgwG.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/finance/%EC%82%BC%EC%84%B1%ED%99%94%EC%9E%AC-028-full-K2SosKxrQEpizllIkxAyrnewkgtxEa.jpg" },
      { brandName: "삼성화재", note: "다이렉트 건강보험료 계산 유도형", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/finance/%EC%82%BC%EC%84%B1%ED%99%94%EC%9E%AC-037-thumb-EKLJMsvSK5xZHTJeO0yHHiNCTXjOZZ.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/finance/%EC%82%BC%EC%84%B1%ED%99%94%EC%9E%AC-037-full-14I12QdGBZpUOii3rEhbyZ2kY0PFfr.jpg" },
      { brandName: "메리츠화재", note: "신규 치아보험 출시 안내", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/finance/%EB%A9%94%EB%A6%AC%EC%B8%A0%ED%99%94%EC%9E%AC-042-thumb-5mSFLHRIGn2c9TieBUu5idP3pnRbDB.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/finance/%EB%A9%94%EB%A6%AC%EC%B8%A0%ED%99%94%EC%9E%AC-042-full-p3Np9uxEPRTqObIBijW359VR4VFohh.jpg" },
      { brandName: "KB손해보험", note: "보험종류 고민 해결형 카피, 캐릭터 사용", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/finance/kb%EC%86%90%ED%95%B4%EB%B3%B4%ED%97%98-044-thumb-1FLRN7N0Av0JOwvEldkjB72gu9hZ5i.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/finance/kb%EC%86%90%ED%95%B4%EB%B3%B4%ED%97%98-044-full-IlI7EJxft09o48pOvtHfQjK33eGsJU.jpg" },
      { brandName: "삼성생명", note: "암보험+뇌심장 특약 결합 상품", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/finance/%EC%82%BC%EC%84%B1%EC%83%9D%EB%AA%85-045-thumb-jvSUSJ0mlGDyyqcazSLTtxigpQwxUz.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/finance/%EC%82%BC%EC%84%B1%EC%83%9D%EB%AA%85-045-full-bKOvwAqPsf44frg9HkLsaz9OYBV6m4.jpg" },
      { brandName: "KB국민카드", note: "일본쇼핑 트래블러스체크카드 프로모션", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/finance/kb%EA%B5%AD%EB%AF%BC%EC%B9%B4%EB%93%9C-046-thumb-6xo4JifPoQA9S7ACdjH6l8wxYnRLUS.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/finance/kb%EA%B5%AD%EB%AF%BC%EC%B9%B4%EB%93%9C-046-full-jjMEoAaOWlNAnEtqp3Xnh45KIGCHfq.jpg" },
      { brandName: "DB손해보험", note: "다이렉트 운전자보험, 상황극 비주얼", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/finance/db%EC%86%90%ED%95%B4%EB%B3%B4%ED%97%98-047-thumb-zs2TN9wl83HlYzbIk7z6kCNzEGJuUL.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/finance/db%EC%86%90%ED%95%B4%EB%B3%B4%ED%97%98-047-full-J2Elfhp74rQ97vgjB8EoB7tGg44w1Q.jpg" },
      { brandName: "SK증권", note: "계좌 이벤트 키보드 키캡 비주얼(S/K종목)", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/finance/sk%EC%A6%9D%EA%B6%8C-049-thumb-Z53I6yxCZYSsrQtgI4xpayP4YYJpB0.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/finance/sk%EC%A6%9D%EA%B6%8C-049-full-XyWdH0ndrsXqUR6aNZIbtLvEbmohNW.jpg" },
      { brandName: "하나카드", note: "VISA&pay 트래블GO 경품 이벤트", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/finance/%ED%95%98%EB%82%98%EC%B9%B4%EB%93%9C-050-thumb-4LtyA4fMVuNOIxI7S0LwaA6bQDrdm9.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/finance/%ED%95%98%EB%82%98%EC%B9%B4%EB%93%9C-050-full-6znYYViEZgdnefsT9GB9cqWDza2Z9Y.jpg" },
      { brandName: "SK증권", note: "계좌 이벤트, 최대 101만원 강조(변형)", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/finance/sk%EC%A6%9D%EA%B6%8C-053-thumb-VkAe9Ja0Qb0SDNPwRA0ApDYVJk6YQi.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/finance/sk%EC%A6%9D%EA%B6%8C-053-full-1NYR7yymT694mJU9XQ0Jc0Yzt3SQGy.jpg" },
      { brandName: "하나카드", note: "트래블GO 발급 1천만원 도전 이벤트", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/finance/%ED%95%98%EB%82%98%EC%B9%B4%EB%93%9C-055-thumb-PEzaE2u69TlLBkEBueVpsFte9GCBlE.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/finance/%ED%95%98%EB%82%98%EC%B9%B4%EB%93%9C-055-full-7NVxtj14fmvbvdhKNDnjVkbazLRWd5.jpg" },
      { brandName: "신한투자증권", note: "슈퍼SOL 자산관리 앱 프로모션", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/finance/%EC%8B%A0%ED%95%9C%ED%88%AC%EC%9E%90%EC%A6%9D%EA%B6%8C-068-thumb-wkfV4guNLvA7L5PPk1obnLK6MSOIQO.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/finance/%EC%8B%A0%ED%95%9C%ED%88%AC%EC%9E%90%EC%A6%9D%EA%B6%8C-068-full-00ZDjy6w3lxYoYLFahJhOCHjOnWQqc.jpg" },
      { brandName: "삼성화재", note: "상해출산보험, 네이버페이 포인트 리워드", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/finance/%EC%82%BC%EC%84%B1%ED%99%94%EC%9E%AC-073-thumb-VZhZ5sKWOnNLAIrf9geO6cKa9AYgRy.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/finance/%EC%82%BC%EC%84%B1%ED%99%94%EC%9E%AC-073-full-QlPP3M6KszT3YPPOQ2Jys34PjSnZB3.jpg" },
      { brandName: "KB국민카드", note: "여름 휴가스팟 취향저격 패키지 비교형", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/finance/kb%EA%B5%AD%EB%AF%BC%EC%B9%B4%EB%93%9C-086-thumb-s9CtqmsxZF0KF4nXnsZkiNcjsky9N9.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/finance/kb%EA%B5%AD%EB%AF%BC%EC%B9%B4%EB%93%9C-086-full-wu468q1t5b0s4H2pZSyyf3AYkhRE3d.jpg" },
      { brandName: "삼성화재", note: "주택화재보험 비피해자 사례형 카피", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/finance/%EC%82%BC%EC%84%B1%ED%99%94%EC%9E%AC-089-thumb-ua1zWW1vtitlhg8zW1Ry6DUVi1SxlP.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/finance/%EC%82%BC%EC%84%B1%ED%99%94%EC%9E%AC-089-full-aShCl0mO8AQduw00xlRppQAr3GD1ka.jpg" },
      { brandName: "KB국민카드", note: "아이 첫통장 개설 프로모션", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/finance/kb%EA%B5%AD%EB%AF%BC%EC%B9%B4%EB%93%9C-097-thumb-n7UFTwDxtzIJjERmONLuxHUDLsaW1Z.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/finance/kb%EA%B5%AD%EB%AF%BC%EC%B9%B4%EB%93%9C-097-full-gkg1gai1PpXDUOdoWCLRjjmaRX0TMG.jpg" },
      { brandName: "하나카드", note: "트래블GO 1천만원 경품 도전(변형)", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/finance/%ED%95%98%EB%82%98%EC%B9%B4%EB%93%9C-100-thumb-LSB9x7pNO0ZK9tVI5EVtNpnMvMAUEY.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/finance/%ED%95%98%EB%82%98%EC%B9%B4%EB%93%9C-100-full-wlMKQ4S92aRT9E4H7X2AXXihsSxNeE.jpg" },
      { brandName: "삼성화재", note: "러닝보험 출시, 3D 캐릭터 러닝 비주얼", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/finance/%EC%82%BC%EC%84%B1%ED%99%94%EC%9E%AC-102-thumb-sH42aMxL6iMrYc8OCxxQdAmWKRbVKB.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/finance/%EC%82%BC%EC%84%B1%ED%99%94%EC%9E%AC-102-full-lU57VNPbKKNvqIQuhncyu7BTkgmm0E.jpg" },
      { brandName: "코인원", note: "비트코인 3만원 즉시지급 이벤트", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/finance/%EC%BD%94%EC%9D%B8%EC%9B%90-105-thumb-55TBDib6SsHtvYAUIHYiiDGiFMDN2a.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/finance/%EC%BD%94%EC%9D%B8%EC%9B%90-105-full-85vZlyep55wQoBO0DnGA4ekcexS182.jpg" },
      { brandName: "KB증권", note: "연금저축 ETF 자산 키우기 게이미피케이션 UI", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/finance/kb%EC%A6%9D%EA%B6%8C-108-thumb-ycLJ6c7CSG4ajgZJkb5DDJNSTYgByv.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/finance/kb%EC%A6%9D%EA%B6%8C-108-full-0sTN9Zpc2b64kZgbWOh0SeRBLn29nQ.jpg" },
      { brandName: "KB증권", note: "주식쿠폰 최대 450만원 이벤트", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/finance/kb%EC%A6%9D%EA%B6%8C-109-thumb-eaqLppkGLcYE8llczuwMN89FOGVVBm.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/finance/kb%EC%A6%9D%EA%B6%8C-109-full-TRFpjOthGxQrjVKR5YB4KQoZUoVgbn.jpg" },
      { brandName: "KB국민카드", note: "3월 신규고객 캐시백 헤택", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/finance/kb%EA%B5%AD%EB%AF%BC%EC%B9%B4%EB%93%9C-142-thumb-LMJ5FXU1p8r3e9fytQaNUP1ffkNtKQ.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/finance/kb%EA%B5%AD%EB%AF%BC%EC%B9%B4%EB%93%9C-142-full-SWl6ocV4CHBUiZVeyzNWQ6veBGtWIp.jpg" },
      { brandName: "KB국민카드", note: "Need Edu카드 교육비 부담 DOWN", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/finance/kb%EA%B5%AD%EB%AF%BC%EC%B9%B4%EB%93%9C-143-thumb-CuWNTvulaneZWjj9ikqtlyo3aEzh5q.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/finance/kb%EA%B5%AD%EB%AF%BC%EC%B9%B4%EB%93%9C-143-full-CwhOZlxHi0IJ9tamxDquPTMtHDh9CT.jpg" },
    ] },
  'shopping': { name: "쇼핑/커머스", items: [
      { brandName: "하기스", note: "기저귀 흡수력 비교 문구형 카피", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/shopping/%ED%95%98%EA%B8%B0%EC%8A%A4-010-thumb-UZGE7BUkVvqoHHN0rPiQdAlQhzx5H7.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/shopping/%ED%95%98%EA%B8%B0%EC%8A%A4-010-full-jfl5a7oGXpvoSqmQA6iUEQ3QCVueCX.jpg" },
      { brandName: "락앤락", note: "미니 텀블러 가벼움 강조, 협업(락인락)", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/shopping/%EB%9D%BD%EC%95%A4%EB%9D%BD-029-thumb-nDYJP9xEPhIE9IieRAorAro3S6bSnj.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/shopping/%EB%9D%BD%EC%95%A4%EB%9D%BD-029-full-DsHchO03rSiNz4UZAUZLPYeEjt1pI1.jpg" },
      { brandName: "위첵", note: "세제 슈퍼적립위크 43% 할인", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/shopping/%EC%9C%84%EC%B2%B5-033-thumb-RZ1VIntYQvfaLO1dOHC3wZMFkp1zEt.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/shopping/%EC%9C%84%EC%B2%B5-033-full-vdtWrwq5FwPG3szREYGZbUk93ShuaE.jpg" },
      { brandName: "파르페by알렉스랑", note: "침구 패밀리세일 85% 할인, 링크코드형", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/shopping/%ED%8C%8C%EB%A5%B4%ED%8E%98by%EC%95%8C%EB%A0%89%EC%8A%A4%EB%9E%91-034-thumb-qfwnpjpAVmdaYcjYw9cnZd3KQx59x7.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/shopping/%ED%8C%8C%EB%A5%B4%ED%8E%98by%EC%95%8C%EB%A0%89%EC%8A%A4%EB%9E%91-034-full-zzGn4etu2qATDr8oLyJMt4pqcEJV4k.jpg" },
      { brandName: "버닝웨이브", note: "EMS 복대 운동기구, 문제해결형 카피", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/shopping/%EB%B2%84%EB%8B%9D%EC%9B%A8%EC%9D%B4%EB%B8%8C-035-thumb-bm3W2i7RHsRkLE8aCklLAzG3IPwrlW.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/shopping/%EB%B2%84%EB%8B%9D%EC%9B%A8%EC%9D%B4%EB%B8%8C-035-full-1Ud7EpgnTdtXhgKiIHSKJAhkUq8JjH.jpg" },
      { brandName: "스파클웨이브", note: "식기세척기 세제 1+1 세일중", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/shopping/%EC%8A%A4%ED%8C%8C%ED%81%B4%EC%9B%A8%EC%9D%B4%EB%B8%8C-056-thumb-jINkaVKoTBD96uIRi6dOVvI9YeDWLH.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/shopping/%EC%8A%A4%ED%8C%8C%ED%81%B4%EC%9B%A8%EC%9D%B4%EB%B8%8C-056-full-7DU43r913vaAf37lj3NIqwCY5jCgIZ.jpg" },
      { brandName: "하기스", note: "네이처메이드 썸머 로션 프로모션", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/shopping/%ED%95%98%EA%B8%B0%EC%8A%A4-058-thumb-iEtvjIYbjANbvLmZxZMi0ZvgfcDRKZ.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/shopping/%ED%95%98%EA%B8%B0%EC%8A%A4-058-full-Vdi8gN5biRwozkkbr9CUBra1mEgrsZ.jpg" },
      { brandName: "NAMUH", note: "구독 이벤트 100만원, 부담 낮춤형 카피", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/shopping/namuh-059-thumb-hIbTtkmMvxrZTSCSUnbSr3tbuOWcxM.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/shopping/namuh-059-full-WBRLjJQfByZmaiSEDziiGoGLMywnXT.jpg" },
      { brandName: "하기스", note: "기저귀 흡수력 1위, 아기 비주얼", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/shopping/%ED%95%98%EA%B8%B0%EC%8A%A4-087-thumb-FKXqmPUTuGeObrqDP4hwhW3pXxZO6p.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/shopping/%ED%95%98%EA%B8%B0%EC%8A%A4-087-full-5ei0CysR8s5B3a7W2maopySjWgOs7t.jpg" },
      { brandName: "마미포코", note: "무표백 소재 기저귀, 제품 나열형", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/shopping/%EB%A7%88%EB%AF%B8%ED%8F%AC%EC%BD%94-088-thumb-KJSGCQXE1BVN9Kw5ZN6BBsza11lwRs.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/shopping/%EB%A7%88%EB%AF%B8%ED%8F%AC%EC%BD%94-088-full-n3EdolUX8PGxp48A9yQ07Qs2BtbgfY.jpg" },
      { brandName: "하기스", note: "매직컴포트 빠른흡수 쾌적함MAX", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/shopping/%ED%95%98%EA%B8%B0%EC%8A%A4-091-thumb-hVTvI7peMoSlP9r75JwIEs0TeWbYXR.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/shopping/%ED%95%98%EA%B8%B0%EC%8A%A4-091-full-gMRXm9WAC1D8SZyMaZepY1jJhivC1S.jpg" },
      { brandName: "넷다세일", note: "테니스 용품 에이더 역대급 할인", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/shopping/%EB%84%B7%EB%8B%A4%EC%84%B8%EC%9D%BC-101-thumb-LmMACHAVXbC6NpITf8iHGaqLqyHuoO.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/shopping/%EB%84%B7%EB%8B%A4%EC%84%B8%EC%9D%BC-101-full-GFEtVPYNvF3IcSnWj76Vv9c6y7hTT6.jpg" },
      { brandName: "NAMUH", note: "응원 프로모션, 축구 모티프 무제한 적립", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/shopping/namuh-106-thumb-DtvkvmxlBsKGSVpt9WINZJJMlyoiEh.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/shopping/namuh-106-full-NSroajxRjlQ4V6wKNd9XzWPEGD80jD.jpg" },
      { brandName: "N스토어(cara)", note: "가정의달 세일, 스마트 디퓨저 기기", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/shopping/n%EC%8A%A4%ED%86%A0%EC%96%B4-cara-127-thumb-JStmajMxjFmmTZ0tH9X89OMTl2zN74.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/shopping/n%EC%8A%A4%ED%86%A0%EC%96%B4-cara-127-full-F7NSJirc8juZXCXK1rtabMxzYxerqq.jpg" },
      { brandName: "홈플러스(Homeplus)", note: "결제 쿠폰 단계별 증정(홈플페이워크)", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/shopping/nhnad-%ED%99%88%ED%94%8C%EB%9F%AC%EC%8A%A4-homeplus-11-thumb-AgJ43pzDTyLOrDIBJMCJA2OFqCY2SR.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/shopping/nhnad-%ED%99%88%ED%94%8C%EB%9F%AC%EC%8A%A4-homeplus-11-full-CxA09eSbIt9l9lDjEe9fNqCJRXCwt0.jpg", ownWork: true },
    ] },
  'beauty': { name: "화장품/뷰티", items: [
      { brandName: "일리윤", note: "선로션 신제품 출시 배너, 제품 라인업 나열형", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/%EC%9D%BC%EB%A6%AC%EC%9C%A4-002-thumb-5aeYcyxnnwQhB4GScsstGspMmp4DTh.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/%EC%9D%BC%EB%A6%AC%EC%9C%A4-002-full-Uq0JTJcIt1z815Jpp4cuGgdIlDUZOv.jpg" },
      { brandName: "비겐(동아제약)", note: "새치 커버 크림톤, 문제 제기형 카피(두피 걱정)", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/%EB%B9%84%EA%B2%90-%EB%8F%99%EC%95%84%EC%A0%9C%EC%95%BD-003-thumb-ePPUCZNV8b8OMTksmOtA8vxfRk1HdY.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/%EB%B9%84%EA%B2%90-%EB%8F%99%EC%95%84%EC%A0%9C%EC%95%BD-003-full-SC4OTtDLQbVr0SUDANIgDjyoejNys0.jpg" },
      { brandName: "센시안(올리브영)", note: "팬티라이너 올영1위 배지 + 가격 강조", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/%EC%84%BC%EC%8B%9C%EC%95%88-%EC%98%AC%EB%A6%AC%EB%B8%8C%EC%98%81-004-thumb-8sLtkovPIQOoLVRkZkZD2V2yJOak9M.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/%EC%84%BC%EC%8B%9C%EC%95%88-%EC%98%AC%EB%A6%AC%EB%B8%8C%EC%98%81-004-full-3MdKrNtiVTYIu5DtzeZRIn6OhjWJ1e.jpg" },
      { brandName: "이니스프리", note: "수분크림 1+1, 스포츠(테니스공) 모티프 배경", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/%EC%9D%B4%EB%8B%88%EC%8A%A4%ED%94%84%EB%A6%AC-007-thumb-HnewEiRsDT2xiiaJKdAIquLuegblzH.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/%EC%9D%B4%EB%8B%88%EC%8A%A4%ED%94%84%EB%A6%AC-007-full-3Grg4LWy2v7lJ0QEk2PUZ9M8Qj83jU.jpg" },
      { brandName: "메디힐", note: "마스크팩 골라담기 라이브 방송 예고 배너", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/%EB%A9%94%EB%94%94%ED%9E%90-011-thumb-8unLCWSa6BmnpzYQ2F8Zzi4FH1gEHq.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/%EB%A9%94%EB%94%94%ED%9E%90-011-full-NyE4xQRkxsVqKsCHdJiX9FHQySDA5F.jpg" },
      { brandName: "마데카셀(올리브영)", note: "손상 피부장벽 케어 크림, 올영단독 배지", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/%EB%A7%88%EB%8D%B0%EC%B9%B4%EC%85%80-%EC%98%AC%EB%A6%AC%EB%B8%8C%EC%98%81-015-thumb-ZAPsuXdydLtmKmfqaytPyvVxXaZolZ.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/%EB%A7%88%EB%8D%B0%EC%B9%B4%EC%85%80-%EC%98%AC%EB%A6%AC%EB%B8%8C%EC%98%81-015-full-GVAaCqtAGm1eQkzcXBomZz9t1DNRQc.jpg" },
      { brandName: "일리윤", note: "선크림 전용 클렌저, 올영단독 1+1", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/%EC%9D%BC%EB%A6%AC%EC%9C%A4-018-thumb-x1CfRau9PMNX2OUW9O7oK6qYUeUbBv.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/%EC%9D%BC%EB%A6%AC%EC%9C%A4-018-full-521Qz1RfnqOYc7Kvmq7TkfUqYGx9gY.jpg" },
      { brandName: "Dr.G", note: "레드블레미쉬 수분크림 100ml 특가", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/dr-g-061-thumb-OXRM7XrvZ1S5cUv6oQtV2Q9QSeDyQV.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/dr-g-061-full-1YbYr5YV3dpiHnElIhbXby0BE759Vy.jpg" },
      { brandName: "아토팜", note: "반값특가, 부모-아이 라이프스타일 컷", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/%EC%95%84%ED%86%A0%ED%8C%9C-063-thumb-HcJziXjSeeEQZgx9QsfRDPqo4kMsvQ.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/%EC%95%84%ED%86%A0%ED%8C%9C-063-full-IXKWv4I8O6Jn4DlOmK59V51wdtzea6.jpg" },
      { brandName: "리얼베리어", note: "수분장벽 선크림 1+1, 올영단독 14%", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/%EB%A6%AC%EC%96%BC%EB%B2%A0%EB%A6%AC%EC%96%B4-064-thumb-pnka7LwFOlzELGeElJ5xsGWrJY5osF.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/%EB%A6%AC%EC%96%BC%EB%B2%A0%EB%A6%AC%EC%96%B4-064-full-WsalKvyQRspXZADTZe3bYCKmks8aP5.jpg" },
      { brandName: "제로이드", note: "수딩크림 올영 오특 한정특가", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/%EC%A0%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-070-thumb-62O1gDEcqlkNGy17NKWHXZlrbhjX96.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/%EC%A0%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-070-full-jI6KheGzUsFlDr7cdTpt3lDqXkKJQa.jpg" },
      { brandName: "리얼베리어", note: "에어컨 속건조 해결 라이브 예고", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/%EB%A6%AC%EC%96%BC%EB%B2%A0%EB%A6%AC%EC%96%B4-071-thumb-DTKjkJy0UAdEW9mQ8bAmOc0xO7q2u4.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/%EB%A6%AC%EC%96%BC%EB%B2%A0%EB%A6%AC%EC%96%B4-071-full-bMYkNzWUb7uPVvLgynvnxTzMYoMdtb.jpg" },
      { brandName: "제로이드", note: "데일리 선크림 올영 기획특가 40%", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/%EC%A0%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-076-thumb-X3izUeE5CtUnlv37aUu8WBbA1Hqdf5.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/%EC%A0%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-076-full-cBkgdICSqOswyqOBhJ6YRwx9R9hHWW.jpg" },
      { brandName: "리얼베리어", note: "익스트림크림 피부진정 47%, 수치강조형", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/%EB%A6%AC%EC%96%BC%EB%B2%A0%EB%A6%AC%EC%96%B4-077-thumb-wlJCyNlfhBdT0ytJZ5KYgwzjFSbnem.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/%EB%A6%AC%EC%96%BC%EB%B2%A0%EB%A6%AC%EC%96%B4-077-full-baH9lTePYWC4W9ViBkw92ztnWpKmhp.jpg" },
      { brandName: "비겐(동아제약)", note: "두피자극 걱정 ZERO, 신제품 비주얼(변형)", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/%EB%B9%84%EA%B2%90-%EB%8F%99%EC%95%84%EC%A0%9C%EC%95%BD-095-thumb-At5BQdH7wIZaT5yU4RBwFrCZEuoIwc.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/%EB%B9%84%EA%B2%90-%EB%8F%99%EC%95%84%EC%A0%9C%EC%95%BD-095-full-gE8ZrX45XZ5r2fK90V7MKj72g3Q149.jpg" },
      { brandName: "제로이드", note: "폼클렌저 대용량 리필기획 6월특가", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/%EC%A0%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-098-thumb-ZfvfVwQbC5vJeDESYBYz5oiLMEORnk.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/%EC%A0%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-098-full-WxzrpTrkCyaFsSm0wEZhOo3GIQlcaW.jpg" },
      { brandName: "리얼베리어", note: "장벽케어 클렌징 신제품, 네이버 단독", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/%EB%A6%AC%EC%96%BC%EB%B2%A0%EB%A6%AC%EC%96%B4-114-thumb-gmaDDxPSk3Cyx1YdHILHaUkdPUmDJt.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/%EB%A6%AC%EC%96%BC%EB%B2%A0%EB%A6%AC%EC%96%B4-114-full-ICBVszCGmwmwzqyJacc3rdd4jQE3Wq.jpg" },
      { brandName: "제로이드", note: "올리브데이 베스트셀러 최대 50%", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/%EC%A0%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-115-thumb-2eNiWsrKW64J52OC7QcsStyKgwnYaC.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/%EC%A0%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-115-full-mPB6BHPwEZuUoL2dwHR70CceUso15E.jpg" },
      { brandName: "순수한면", note: "쿨링브리즈 생리대 1+1, 온도 수치 강조", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/%EC%88%9C%EC%88%98%ED%95%9C%EB%A9%B4-117-thumb-P2mZPvtpBiPQAq92Ixbbc0e4Pp3IdB.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/%EC%88%9C%EC%88%98%ED%95%9C%EB%A9%B4-117-full-OFPC8D65Cm0b6Ax8cFeJMzLt3lYnwe.jpg" },
      { brandName: "아로마티카", note: "쇼핑페스타 최대 71%, 자연 배경", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/%EC%95%84%EB%A1%9C%EB%A7%88%ED%8B%B0%EC%B9%B4-119-thumb-wTizGNnyviDUTMW7RxwMdjoVwqVvif.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/%EC%95%84%EB%A1%9C%EB%A7%88%ED%8B%B0%EC%B9%B4-119-full-9orNm6amZOn9lsrvpiyzYEPUdJ7Nlz.jpg" },
      { brandName: "제로이드", note: "저자극 수딩로션 23% 할인", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/%EC%A0%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-121-thumb-PUb3UvCPt7e5pJ9l58WKvO3hbHyFjJ.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/%EC%A0%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-121-full-GusWuMv8bbDXvkpT8enYIonn3HIM6F.jpg" },
      { brandName: "제로이드", note: "수분진정 UP, 올영PICK 배지", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/%EC%A0%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-122-thumb-nmk4lBhFajdptr1ujvnUAyfiErIYtt.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/%EC%A0%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-122-full-yRNSTYOAhVV6YXBa8d5XuXMCohioWR.jpg" },
      { brandName: "제로이드", note: "수분&진정 치트키, 오늘의특가", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/%EC%A0%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-123-thumb-02s0Qjw4Wlo8Dli360I4JIgmR4d0Lc.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/%EC%A0%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-123-full-k2PlkAinWMILsTRNp8KyqU9cOqif7U.jpg" },
      { brandName: "제로이드", note: "올영1위 선크림 단10일 50%", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/%EC%A0%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-124-thumb-q1egASpUv94HV7RAtVt74Yh8SkaZBd.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/%EC%A0%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-124-full-zOMePJUfPxzND3YYSOBiqSaJvGmFuP.jpg" },
      { brandName: "제로이드", note: "핌프로브 레드컨트롤 크림 트러블케어", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/%EC%A0%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-128-thumb-4fsGcSrC6DenNAB2EPkT95lRW3JbNA.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/%EC%A0%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-128-full-EYXBx1I6JHu3rkHcIc2OLbuawxtEEH.jpg" },
      { brandName: "제로이드", note: "핌프로브 레드컨트롤크림, 트러블 피부 치트키", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/%EC%A0%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-131-thumb-vp6QEBGCZ292klan6NyR7Q84QyGhBZ.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/%EC%A0%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-131-full-Lo5SvE1J30PPxjYWv8uAtIaOh4PBwn.jpg" },
      { brandName: "제로이드", note: "인텐시브크림+수딩크림 세트, 장벽+보습", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/%EC%A0%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-132-thumb-TeLi5l2cihlIiTlhIsXlJETL0bjHtX.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/%EC%A0%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-132-full-GZnpKqaAdFVOiCIXCLo0XOcwYw9Y0R.jpg" },
      { brandName: "제로이드", note: "인텐시브 촉촉함 지속, 120h 보습", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/%EC%A0%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-133-thumb-13YP9GxK0fodKE2ofbVlmZ7mDC9TX3.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/%EC%A0%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-133-full-YtyDmlX4bHmPGMrkZqHh2xTcPQVmUL.jpg" },
      { brandName: "제로이드", note: "포밍클렌저 리필기획 세트 23%", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/%EC%A0%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-134-thumb-TdiJLgNMCCPyPHDw8MZEuZSW6MO6y8.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/%EC%A0%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-134-full-BxpS9PbVJJMaE389JHiVm77xjMpaQs.jpg" },
      { brandName: "제로이드", note: "트러블 치트키크림, 올영PICK 특가 도착", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/%EC%A0%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-136-thumb-Z3iwNuXJpXyURQryELYbzQ9kKN3Ckr.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/%EC%A0%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-136-full-54E9loCL5D9kbAcNDbMePcQTMJhdWp.jpg" },
      { brandName: "니베아", note: "SOS케어 바디로션 2개세트 58%", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/%EB%8B%88%EB%B2%A0%EC%95%84-145-thumb-uxIDMVsHnKmx60xBQ362LZ0Y8qxVud.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/%EB%8B%88%EB%B2%A0%EC%95%84-145-full-PfaHjysCyVFTTyrruGeItaIaVMke2R.jpg" },
      { brandName: "아모레퍼시픽(신세계쇼핑)", note: "가정의 달 맞이 헤라·아이오페·한율 등 라인업 37% 할인", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/nhnad-%EC%95%84%EB%AA%A8%EB%A0%88%ED%8D%BC%EC%8B%9C%ED%94%BD-%EC%8B%A0%EC%84%B8%EA%B3%84%EC%87%BC%ED%95%91-01-thumb-ulGIshvEfu9Hk7jkOahcQ8ahHtQ27I.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/nhnad-%EC%95%84%EB%AA%A8%EB%A0%88%ED%8D%BC%EC%8B%9C%ED%94%BD-%EC%8B%A0%EC%84%B8%EA%B3%84%EC%87%BC%ED%95%91-01-full-WUu0U2rOWA8QWPolMGZrXuxXVNYWsY.jpg", ownWork: true },
      { brandName: "보다나(vodana)", note: "빗고데기 플립 Before/After 모델컷으로 효과 강조", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/nhnad-%EB%B3%B4%EB%8B%A4%EB%82%98-vodana-02-thumb-epuks0lpxIz8DzTsvj4LI15cRehqay.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/nhnad-%EB%B3%B4%EB%8B%A4%EB%82%98-vodana-02-full-N3xR4L9kiGiK5z8Ra4QchoWLhkFBVu.jpg", ownWork: true },
      { brandName: "지숩(j'SOOP)", note: "환절기 화장품 라인업 최대 69% 특가, 카카오 메인톡딜", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/nhnad-%EC%A7%80%EC%88%A9-j-soop-03-thumb-77mvuVrkJ8fzf6jxQ2lM2PzBsqUnXX.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/nhnad-%EC%A7%80%EC%88%A9-j-soop-03-full-QCqK2cMwXKev0IWexUV0yYySg9Y3nD.jpg", ownWork: true },
      { brandName: "아토팜(ATOPALM x 11번가)", note: "단3일 1+1 증정 SALE, 봄맞이 프로모션", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/nhnad-%EC%95%84%ED%86%A0%ED%8C%9C-atopalm-x-11%EB%B2%88%EA%B0%80-10-thumb-BMQiQAu6gw5aKV9apCSsmGM1CLReQU.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/beauty/nhnad-%EC%95%84%ED%86%A0%ED%8C%9C-atopalm-x-11%EB%B2%88%EA%B0%80-10-full-OW67M10S8r4XIRZRHgZgfUlZIqYkYQ.jpg", ownWork: true },
    ] },
  'telecom': { name: "통신", items: [
      { brandName: "kt M mobile", note: "5G 데이터 요금제 가격 강조형", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/telecom/kt-m-mobile-031-thumb-TTVTfQTInIkW5y4WtUd1iZvXml60xY.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/telecom/kt-m-mobile-031-full-Ei4WM2DQtd6UTzhiWtot5OFgXfBkRC.jpg" },
      { brandName: "kt HCN", note: "통신비 반값 강조, 캐릭터 일러스트", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/telecom/kt-hcn-041-thumb-Lmj2d7gv2FkeJiqw4LRxB7SOr4pxWS.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/telecom/kt-hcn-041-full-9E9DDgCIWVw48arYcABnHShYMX6hyz.jpg" },
      { brandName: "kt HCN", note: "상담만 받아도 기프티콘 증정형", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/telecom/kt-hcn-043-thumb-b9Ok255GeJo3rZ9hpfHgbYzmSSI0Hs.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/telecom/kt-hcn-043-full-HNN7Ib1f0GgsOTT0VmkKr3H1QWI4nK.jpg" },
      { brandName: "SKT", note: "epay 2개월 0원 요금제, 다크모드 UI 비주얼", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/telecom/skt-060-thumb-rHlZ9Qa6gptRgsLxVtiB2c0yjcsxyX.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/telecom/skt-060-full-UJ2TpZxcCTZ88vSdtpSZAZd8Zr5LAe.jpg" },
      { brandName: "LG U+", note: "유쓰 AI쇼츠패스타임, 실사 컷 활용", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/telecom/lg-u-065-thumb-vS18gTzsHlRwHRi5O24VlXteB1953q.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/telecom/lg-u-065-full-wxybofe8lbmbrHz3IuQFcnC1dHjVmx.jpg" },
      { brandName: "우리WON모바일", note: "데이터무제한 통신비 자유선언", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/telecom/%EC%9A%B0%EB%A6%ACwon%EB%AA%A8%EB%B0%94%EC%9D%BC-147-thumb-C3HGYTc4rmPNEiFw2W3R3EX55Qo6fs.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/telecom/%EC%9A%B0%EB%A6%ACwon%EB%AA%A8%EB%B0%94%EC%9D%BC-147-full-oY2VRpnxzK5y2m7YM0m1ya8GtsKMAC.jpg" },
      { brandName: "LG U+", note: "5월 한정 첫달 무료요금제, N페이 적립 강조", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/telecom/nhnad-lg-u-05-thumb-al97i0c0g2TPhXTd2tHTZSYHbYCXLL.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/telecom/nhnad-lg-u-05-full-qPWW0XBYFFQNK7SxaijMc1PNBEdWIM.jpg", ownWork: true },
    ] },
  'food': { name: "식품/외식", items: [
      { brandName: "매일유업", note: "아몬드브리즈 적립+세일 프로모션", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/food/%EB%A7%A4%EC%9D%BC%EC%9C%A0%EC%97%85-032-thumb-QjzrptTJr9yBd2LWI1uYgtMgZASrJ4.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/food/%EB%A7%A4%EC%9D%BC%EC%9C%A0%EC%97%85-032-full-K6BkPKPaDvhY6av9Og14CxPTakLEdu.jpg" },
      { brandName: "교촌치킨", note: "카카오프렌즈 콜라보 응원 캠페인", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/food/%EA%B5%90%EC%B4%8C%EC%B9%98%ED%82%A8-052-thumb-duZnru35uss1Jh51IJlgaAusJN1flW.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/food/%EA%B5%90%EC%B4%8C%EC%B9%98%ED%82%A8-052-full-00XwADXgZM9h8Sd01dXrnUC1l0zVdx.jpg" },
      { brandName: "드시모네", note: "키즈요거트 최고 30% 사은품 증정", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/food/%EB%93%9C%EC%8B%9C%EB%AA%A8%EB%84%A4-069-thumb-hiw329ulOTzkpL0OeuPyDoIYlh9XdE.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/food/%EB%93%9C%EC%8B%9C%EB%AA%A8%EB%84%A4-069-full-WnWr0Q4Rgx5cxsp5pi0w1knaesuxfz.jpg" },
      { brandName: "매일유업", note: "UF 락토프리 소화잘되는 우유", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/food/%EB%A7%A4%EC%9D%BC%EC%9C%A0%EC%97%85-079-thumb-zsqfrc5QdTMtdaqXRst6Mk7bxBSmXB.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/food/%EB%A7%A4%EC%9D%BC%EC%9C%A0%EC%97%85-079-full-uJbYCszsAOUyj4ssoCrwFMMh7EaBaY.jpg" },
      { brandName: "드시모네", note: "정기구독 최저 10% 트럭 비주얼", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/food/%EB%93%9C%EC%8B%9C%EB%AA%A8%EB%84%A4-099-thumb-e9p8H714fjh13ZXtDynL0XCSKY1Q7b.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/food/%EB%93%9C%EC%8B%9C%EB%AA%A8%EB%84%A4-099-full-33M9Fs8yU8iHmBB505Usu1xEgUe4Xs.jpg" },
      { brandName: "스타벅스", note: "카페라떼 컵커피 20컵 0원 이벤트", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/food/%EC%8A%A4%ED%83%80%EB%B2%85%EC%8A%A4-112-thumb-7QoKV9yo5ZMM8NjvPd5aSVYmE6jhiw.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/food/%EC%8A%A4%ED%83%80%EB%B2%85%EC%8A%A4-112-full-JETOPVpKqfqZHfXS2gi6o0CGhF28P8.jpg" },
      { brandName: "조선호텔", note: "국내산 포기김치, 실물 음식 사진 활용", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/food/nhnad-%EC%A1%B0%EC%84%A0%ED%98%B8%ED%85%94-06-thumb-qS0LF30uZI8QsfjWUjrQDWhlNXChZr.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/food/nhnad-%EC%A1%B0%EC%84%A0%ED%98%B8%ED%85%94-06-full-zaAP8fHzMFtR0qA1caJ3WNCPRbLl22.jpg", ownWork: true },
    ] },
  'travel': { name: "여행", items: [
      { brandName: "인스파이어", note: "썸머 플레이케이션, 할인율 강조 배지", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/travel/%EC%9D%B8%EC%8A%A4%ED%8C%8C%EC%9D%B4%EC%96%B4-048-thumb-YZnlMJFH7vSdqkGb3pA6u0larFUZDA.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/travel/%EC%9D%B8%EC%8A%A4%ED%8C%8C%EC%9D%B4%EC%96%B4-048-full-b7nUWyW0Nlt9Za52YlScLe1lN2eIbJ.jpg" },
      { brandName: "엔젤카(angelcar)", note: "제주도 렌터카 중화권 대상 광고, 중국어 카피", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/travel/nhnad-%EC%97%94%EC%A0%A4%EC%B9%B4-angelcar-08-thumb-BaCmknVK65Sox4d3lhYAJVPY4rLUiI.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/travel/nhnad-%EC%97%94%EC%A0%A4%EC%B9%B4-angelcar-08-full-XSTsEVqz5YJXWVG1KynMJ899lQt2tK.jpg", ownWork: true },
      { brandName: "엔젤카(angelcar)", note: "제주도 렌터카, 중국어 카피 + 캐릭터 일러스트", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/travel/nhnad-%EC%97%94%EC%A0%A4%EC%B9%B4-angelcar-09-thumb-jURnQ6O8pSt4sYf33HfqovLh2KHlBo.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/travel/nhnad-%EC%97%94%EC%A0%A4%EC%B9%B4-angelcar-09-full-LQYsh9EKqsIeTu1tGHyZB6JzrmnIhm.jpg", ownWork: true },
    ] },
  'electronics': { name: "가전/IT", items: [
      { brandName: "로보락", note: "로봇청소기 신혼 특가 배너, 진한 톤 배경에 % 강조", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/electronics/%EB%A1%9C%EB%B3%B4%EB%9D%BD-001-thumb-ySQ7WllrEQC8a5qxKi26kYy8gqPDmI.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/electronics/%EB%A1%9C%EB%B3%B4%EB%9D%BD-001-full-fdrYBN66K5agAHo2MFgXJrN5Pw8wng.jpg" },
      { brandName: "캐리어", note: "여름 가전 필수템 최대 89% 할인", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/electronics/%EC%BA%90%EB%A6%AC%EC%96%B4-025-thumb-ZAB4dguLB28y0SFtby2rivpUHivtDM.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/electronics/%EC%BA%90%EB%A6%AC%EC%96%B4-025-full-JWM2YXwDRQag6BQcHsRTMeaqCGK9f5.jpg" },
      { brandName: "쿠쿠", note: "음식물처리기 라이브 방송 예고", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/electronics/%EC%BF%A0%EC%BF%A0-026-thumb-X3TFLlwAy4HRD5jpqjEN64Rf2LDUMQ.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/electronics/%EC%BF%A0%EC%BF%A0-026-full-OtzvMgdhigdtu1qfCsoeO7UP4lH7jl.jpg" },
      { brandName: "NINJA", note: "블렌더/에어프라이어 라이브 특가", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/electronics/ninja-038-thumb-WjFG3i6slQ0tCHnJxMDmDx0nraRVsI.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/electronics/ninja-038-full-9ZgqDEKVUyz7MAoOuxg1PPw4bLL41R.jpg" },
      { brandName: "쿠쿠", note: "쿠쿠데이 클리어런스 특가, 가전 다품목", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/electronics/%EC%BF%A0%EC%BF%A0-067-thumb-Dv5kDSgY1HMXZQm6R4wNJ87y8bi0pN.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/electronics/%EC%BF%A0%EC%BF%A0-067-full-BxNumWHUx5qc9I71BXxVrZAyT4cbn2.jpg" },
      { brandName: "더스크랙", note: "마사지건 강도 비주얼, 네온 이펙트", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/electronics/%EB%8D%94%EC%8A%A4%ED%81%AC%EB%9E%99-072-thumb-mfb8KxLXLeTLfXeDp7Awt51J3Rw6uv.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/electronics/%EB%8D%94%EC%8A%A4%ED%81%AC%EB%9E%99-072-full-s58uTkq1hf6hqIqUuwbfCJ6x98XKh3.jpg" },
      { brandName: "LG전자", note: "NANO TV 19일특가, 할인율 강조", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/electronics/lg%EC%A0%84%EC%9E%90-116-thumb-vddQG6NXTGYM8wlZT2a2CnnFxn08SW.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/electronics/lg%EC%A0%84%EC%9E%90-116-full-NKweIwW7XElS2e3ysaLtxvM2fTPpt1.jpg" },
      { brandName: "로보락", note: "S10 MaxV Ultra 런칭 세일, 로봇청소기 3종", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/electronics/%EB%A1%9C%EB%B3%B4%EB%9D%BD-148-thumb-tifBemfCpgSZ2pQkYGaS0wQnrqorzs.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/electronics/%EB%A1%9C%EB%B3%B4%EB%9D%BD-148-full-Dk68GWY4WYbrcFFYRSWJb8J8tC9pYx.jpg" },
      { brandName: "삼성전자(U+공식온라인스토어)", note: "갤럭시Z폴드7·플립7 감사페스티벌 20% 혜택", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/electronics/nhnad-%EC%82%BC%EC%84%B1%EC%A0%84%EC%9E%90-u-%EA%B3%B5%EC%8B%9D%EC%98%A8%EB%9D%BC%EC%9D%B8%EC%8A%A4%ED%86%A0%EC%96%B4-04-thumb-55t7HCoWZ8qMiVntrNzUD8AZVMIZkR.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/electronics/nhnad-%EC%82%BC%EC%84%B1%EC%A0%84%EC%9E%90-u-%EA%B3%B5%EC%8B%9D%EC%98%A8%EB%9D%BC%EC%9D%B8%EC%8A%A4%ED%86%A0%EC%96%B4-04-full-2t7UKdwWKvuIyaLAWhGcLwNQB5fvao.jpg", ownWork: true },
      { brandName: "삼성전자(U+공식온라인스토어)", note: "갤럭시S26+워치 중복 더블혜택, 가격 비교표 형식", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/electronics/nhnad-%EC%82%BC%EC%84%B1%EC%A0%84%EC%9E%90-u-%EA%B3%B5%EC%8B%9D%EC%98%A8%EB%9D%BC%EC%9D%B8%EC%8A%A4%ED%86%A0%EC%96%B4-07-thumb-BCVog3zJMovNhedEUvHf77yQFFDoB2.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/electronics/nhnad-%EC%82%BC%EC%84%B1%EC%A0%84%EC%9E%90-u-%EA%B3%B5%EC%8B%9D%EC%98%A8%EB%9D%BC%EC%9D%B8%EC%8A%A4%ED%86%A0%EC%96%B4-07-full-cjX5IZZijfuDcdu3ApSK0qCiiV6dxS.jpg", ownWork: true },
    ] },
  'automotive': { name: "자동차", items: [
      { brandName: "불스원", note: "카케이션 여름 자동차용품 프로모션", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/automotive/%EB%B6%88%EC%8A%A4%EC%9B%90-022-thumb-kThIhSePm69suwRCWmihQe6tELRUaw.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/automotive/%EB%B6%88%EC%8A%A4%EC%9B%90-022-full-EdxefjDHKyTnmtquB3dTQHo6Jozhgb.jpg" },
      { brandName: "현대차", note: "여름맞이 헤택 패키지, 아이스박스 비주얼", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/automotive/%ED%98%84%EB%8C%80%EC%B0%A8-036-thumb-v5KyAHNzex6Xu1mINmvi9td33krQyf.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/automotive/%ED%98%84%EB%8C%80%EC%B0%A8-036-full-xSYnonKebHQrvbGwqEbsGeKui3y7ZI.jpg" },
    ] },
  'education': { name: "교육", items: [
      { brandName: "스마트올", note: "한글 학습 완벽 마스터 타이밍 강조", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/education/%EC%8A%A4%EB%A7%88%ED%8A%B8%EC%98%AC-027-thumb-p4kfPYcVYkcMcWo6XBmCgpXIBiTi4F.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/education/%EC%8A%A4%EB%A7%88%ED%8A%B8%EC%98%AC-027-full-zWNBdAkWbQZWy6q4Fe0x0ewASn7Asc.jpg" },
      { brandName: "밀크T", note: "무료체험 선물 증정 프로모션", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/education/%EB%B0%80%ED%81%ACt-051-thumb-EmkrUg6GLpW2p3YZhIpvyAcvrNI5kJ.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/education/%EB%B0%80%ED%81%ACt-051-full-tWK478hgb5mS1WQWLRirTMTNOdPkNE.jpg" },
      { brandName: "밀크T", note: "무료체험 선물 팡팡, 여름 비주얼", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/education/%EB%B0%80%ED%81%ACt-054-thumb-4cPDN3kdrOe1xk3L3jwRRXSusk8m6b.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/education/%EB%B0%80%ED%81%ACt-054-full-ygQ0zJzAtLRHesEySaYTXdDVSL7EjI.jpg" },
      { brandName: "빨간펜", note: "AI 맞춤학습, 연예인 모델", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/education/%EB%B9%A8%EA%B0%84%ED%8E%9C-120-thumb-3b2zDOr0UtSUZjJjeU0xbwuh0hLUyf.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/education/%EB%B9%A8%EA%B0%84%ED%8E%9C-120-full-GszkIbMOCF39mtG7HA7CGSIo6E75Ah.jpg" },
    ] },
  'healthcare': { name: "헬스케어/제약", items: [
      { brandName: "락토핏", note: "프로바이오틱스 인체적용시험 결과 수치 제시형", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/healthcare/%EB%9D%BD%ED%86%A0%ED%95%8F-006-thumb-t8PUhPykIgVQQPkuGZRAgSQ01FyNLo.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/healthcare/%EB%9D%BD%ED%86%A0%ED%95%8F-006-full-0hfjwdhtd1808MS4O3RsA5MwIG2dDG.jpg" },
      { brandName: "락토핏", note: "컬리 단독 신제품 런칭 배너", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/healthcare/%EB%9D%BD%ED%86%A0%ED%95%8F-008-thumb-73x299Cpy2gjPz6ep0x5XORZfNfIiO.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/healthcare/%EB%9D%BD%ED%86%A0%ED%95%8F-008-full-yZ4cocCd7SPfIGGwkkW0jNmpsJMBrd.jpg" },
      { brandName: "종근당건강", note: "오메가3 시사회 이벤트 콜라보 배너", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/healthcare/%EC%A2%85%EA%B7%BC%EB%8B%B9%EA%B1%B4%EA%B0%95-012-thumb-ox61xThOCB18KUneoSFSofiD2Ppy0D.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/healthcare/%EC%A2%85%EA%B7%BC%EB%8B%B9%EA%B1%B4%EA%B0%95-012-full-eNCtIPyLddE2DPF367yb1WSb1DLapc.jpg" },
      { brandName: "락토핏", note: "생유산균 100억보장 컬리온리 배지", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/healthcare/%EB%9D%BD%ED%86%A0%ED%95%8F-013-thumb-2vNmi8TDuKl1WzUQbMhpSYQCeUU4I9.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/healthcare/%EB%9D%BD%ED%86%A0%ED%95%8F-013-full-1WzEhu7BTAdPFG1x04r92RmIMFMb4f.jpg" },
      { brandName: "종근당건강", note: "오메가3 시사회 이벤트 배너(변형)", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/healthcare/%EC%A2%85%EA%B7%BC%EB%8B%B9%EA%B1%B4%EA%B0%95-016-thumb-dSAXypf5KXnGEcRetLjefzUWo6E4bR.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/healthcare/%EC%A2%85%EA%B7%BC%EB%8B%B9%EA%B1%B4%EA%B0%95-016-full-8Xc3HfS349q1Gb0naLNza5ReHDX2IS.jpg" },
      { brandName: "락토핏", note: "컬리 단독 유산균 프라임 신제품", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/healthcare/%EB%9D%BD%ED%86%A0%ED%95%8F-019-thumb-DOwLfc2uRVxQJKj094kRSkV4qMiw47.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/healthcare/%EB%9D%BD%ED%86%A0%ED%95%8F-019-full-M6stqw0gELH8XDn8PxkJOG0ASpPhr5.jpg" },
      { brandName: "락토핏", note: "컬리 단독 유산균 프라임 출시(변형)", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/healthcare/%EB%9D%BD%ED%86%A0%ED%95%8F-023-thumb-xn6Op39FSprFYTXb5xXcQvk0v1uj8z.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/healthcare/%EB%9D%BD%ED%86%A0%ED%95%8F-023-full-3BIxfqXSFcaE1a8UVFgpWtMYxyYhhq.jpg" },
      { brandName: "대원제약", note: "헤모콜라겐 트렌드쇼미5 콜라보, 연예인 모델", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/healthcare/%EB%8C%80%EC%9B%90%EC%A0%9C%EC%95%BD-039-thumb-xSudtGwzqOl9aVhA12OETkCfxYyc6f.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/healthcare/%EB%8C%80%EC%9B%90%EC%A0%9C%EC%95%BD-039-full-28BFmqDBWP2IQUnJIWIMg78kkguMqC.jpg" },
      { brandName: "동화약품", note: "MgLAB 액상 글루콘산 마그네슘, 스트레스 카피", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/healthcare/mglab-062-thumb-PBpJxaePXMRGTNtI8c6yZxk6ZkVwZb.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/healthcare/mglab-062-full-H3YY7u4C1VgesC8Uippfe2BwsMyRWM.jpg" },
      { brandName: "동화약품", note: "베러(BETTER) 식물성 멜라토닌 수면 영양제", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/healthcare/%EB%B2%A0%EB%9F%AC-better-066-thumb-TniAliaX8u6uWeQelvp6GLSpL0eses.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/healthcare/%EB%B2%A0%EB%9F%AC-better-066-full-jdFSGu4yK7Elvi3CoTqbOteY6LT9Zs.jpg" },
      { brandName: "대원제약", note: "꿀잠샷 올영단독기획 12+2포", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/healthcare/%EB%8C%80%EC%9B%90%EC%A0%9C%EC%95%BD-078-thumb-D4s5VO0Bbr2ZpOzxF6xaSaOWNAwNHa.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/healthcare/%EB%8C%80%EC%9B%90%EC%A0%9C%EC%95%BD-078-full-NwAqcgPmgIUT9J8OE3WKY0F4ZODv8Z.jpg" },
      { brandName: "대원제약", note: "꿀잠샷 올영PICK 31%(변형)", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/healthcare/%EB%8C%80%EC%9B%90%EC%A0%9C%EC%95%BD-080-thumb-AD5oJwvE98ewU4mDHkBWEqkH9vsj8b.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/healthcare/%EB%8C%80%EC%9B%90%EC%A0%9C%EC%95%BD-080-full-CfhsKcjBVYoYYcg9XVLz0Nm6zaUZMy.jpg" },
      { brandName: "대원제약", note: "꿀잠샷 수면패턴 되찾는 비결(변형)", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/healthcare/%EB%8C%80%EC%9B%90%EC%A0%9C%EC%95%BD-081-thumb-JAqYcCfnnAjlODpiSpTBtRJljoTBUL.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/healthcare/%EB%8C%80%EC%9B%90%EC%A0%9C%EC%95%BD-081-full-FUWe9JULzbdGJH4Mv3L1749TPXl0ra.jpg" },
      { brandName: "대원제약", note: "꿀잠샷 올리브영1위 배지(변형)", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/healthcare/%EB%8C%80%EC%9B%90%EC%A0%9C%EC%95%BD-082-thumb-ybENl1FOqYj8DXGBS7VdbEDbcZvA0X.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/healthcare/%EB%8C%80%EC%9B%90%EC%A0%9C%EC%95%BD-082-full-LPyOaW6L0e7UgWopOJ2TkwX7DonpQ7.jpg" },
      { brandName: "대원제약", note: "꿀잠샷 자물기 어려운 밤 타겟팅(변형)", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/healthcare/%EB%8C%80%EC%9B%90%EC%A0%9C%EC%95%BD-083-thumb-twC9EfJciUIrc3aImQNEaplEQdlXnQ.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/healthcare/%EB%8C%80%EC%9B%90%EC%A0%9C%EC%95%BD-083-full-9pVKrUJPMmXwSMOKL5r0yN7TOjrVCw.jpg" },
      { brandName: "동화약품(부채표)", note: "50대 활력 영양제, 하루 1천원대 가격 강조", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/healthcare/%EB%8F%99%ED%99%94%EC%95%BD%ED%92%88-%EB%B6%80%EC%B1%84%ED%91%9C-085-thumb-sdIC414ZlM4jd00fPC0GGDXCXVsoFD.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/healthcare/%EB%8F%99%ED%99%94%EC%95%BD%ED%92%88-%EB%B6%80%EC%B1%84%ED%91%9C-085-full-5SohWw5U0ifqpf8ugNGokwRjfUHOuZ.jpg" },
      { brandName: "종근당건강", note: "프로메가 알티지 트리플S 런칭 혜택", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/healthcare/%EC%A2%85%EA%B7%BC%EB%8B%B9%EA%B1%B4%EA%B0%95-090-thumb-XhqpT5EtL7FR2Jy3PCoiaG5a1P9Ttb.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/healthcare/%EC%A2%85%EA%B7%BC%EB%8B%B9%EA%B1%B4%EA%B0%95-090-full-22kpDhZAQb0KeNZCFiHhYvELIN1M43.jpg" },
      { brandName: "대원제약", note: "꿀잠샷 수면패턴(변형2)", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/healthcare/%EB%8C%80%EC%9B%90%EC%A0%9C%EC%95%BD-092-thumb-AKZpAafv8pVmlIV0j9YlpE7c0GJnI6.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/healthcare/%EB%8C%80%EC%9B%90%EC%A0%9C%EC%95%BD-092-full-lDY7LsgOVfLV7C3ifgvBmWkKVmU1k3.jpg" },
      { brandName: "대원제약", note: "꿀잠샷 자기전 한포 수면공식", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/healthcare/%EB%8C%80%EC%9B%90%EC%A0%9C%EC%95%BD-094-thumb-6XcS3zS9PaJ7FK2wYDUdosfFS3aDJy.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/healthcare/%EB%8C%80%EC%9B%90%EC%A0%9C%EC%95%BD-094-full-UrWAkJvnQNCw62zcKpDFE8KftxmxBQ.jpg" },
      { brandName: "대원제약", note: "꿀잠샷 매일밤 푹, 야경 배경", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/healthcare/%EB%8C%80%EC%9B%90%EC%A0%9C%EC%95%BD-096-thumb-a64X2s6SXFcrzVG22WovJtef03lDFM.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/healthcare/%EB%8C%80%EC%9B%90%EC%A0%9C%EC%95%BD-096-full-61Gfn9iJGWNr5gUYfkQSPbpGuVNp8T.jpg" },
      { brandName: "락토핏", note: "슈퍼슬림 여름준비, 튜브 비주얼", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/healthcare/%EB%9D%BD%ED%86%A0%ED%95%8F-103-thumb-ckO0MJBIY3Qr9TuNDiyLtJgpPOasbD.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/healthcare/%EB%9D%BD%ED%86%A0%ED%95%8F-103-full-26RjUVhCU9a77ecTsBqReofzaNDnDQ.jpg" },
      { brandName: "Vitawise", note: "멀티프로 츄 컨디션 관리 정기구독", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/healthcare/vitawise-104-thumb-vschWDSJgvvx21KFrOYoEKZC5YJhLj.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/healthcare/vitawise-104-full-2QnTstTEphQfSMmNDjBI7vdc7pPy0u.jpg" },
      { brandName: "락토핏", note: "다이어트 최대 61% 할인", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/healthcare/%EB%9D%BD%ED%86%A0%ED%95%8F-107-thumb-5lShbUZ2cOwkuzFRcwZ0RsImALoMoy.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/healthcare/%EB%9D%BD%ED%86%A0%ED%95%8F-107-full-KsGymlfezNyZU3utEXfE0nKqFvCvbq.jpg" },
      { brandName: "디지로카", note: "종합영양제 이달의혜택 최대16%", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/healthcare/%EB%94%94%EC%A7%80%EB%A1%9C%EC%B9%B4-129-thumb-fvacmwg0FLCieHDeQmjun1ONLwO3wy.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/healthcare/%EB%94%94%EC%A7%80%EB%A1%9C%EC%B9%B4-129-full-MLjSJUvcKYtd7QoQFKtEJGPwrCsIrN.jpg" },
      { brandName: "Alive!", note: "남성 종합비타민 포맨, 쿠팡 에너지 강조", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/healthcare/alive-138-thumb-uesQnEiolnTkBxlVsXUMxpCgF1AESD.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/healthcare/alive-138-full-FO4lyWITQwRYEFIpQ02z2KxcNL0cXp.jpg" },
      { brandName: "Alive!", note: "포맨 80정 쿠팡골드박스 역대급 할인", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/healthcare/alive-139-thumb-3cnjB0Fz8IGnj6DvVNHYCHA93OWGpg.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/healthcare/alive-139-full-QZ8L77PYtvfnfrHeZlugVrwQxKhnw2.jpg" },
      { brandName: "트루바이타민(Denps)", note: "9주년 비타민 습관 스페셜 쿠폰", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/healthcare/%ED%8A%B8%EB%A3%A8%EB%B0%94%EC%9D%B4%ED%83%80%EB%AF%BC-denps-140-thumb-3y8XscjJ3wJu1UPEHWjK7ODRb2WFyO.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/healthcare/%ED%8A%B8%EB%A3%A8%EB%B0%94%EC%9D%B4%ED%83%80%EB%AF%BC-denps-140-full-1JaMpVE4mwZTTXVsfLH991KXby9fGO.jpg" },
      { brandName: "일동후디스", note: "파이토좀 커큐민 생체흡수율 29배", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/healthcare/%EC%9D%BC%EB%8F%99%ED%9B%84%EB%94%94%EC%8A%A4-141-thumb-wjO0ZtOMDpGZLBlNoA8GVKBqj4pP8H.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/healthcare/%EC%9D%BC%EB%8F%99%ED%9B%84%EB%94%94%EC%8A%A4-141-full-oNsJL7RbL7nEHCPLWdq7mBp6mePtrh.jpg" },
      { brandName: "종근당건강", note: "창립30주년 프로메가 오메가3 42%", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/healthcare/%EC%A2%85%EA%B7%BC%EB%8B%B9%EA%B1%B4%EA%B0%95-144-thumb-p0tiABfHNYnO7QczoRlxAYYtr1YEUt.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/healthcare/%EC%A2%85%EA%B7%BC%EB%8B%B9%EA%B1%B4%EA%B0%95-144-full-GLFfVs4SKw5b8co9BV1WQERHQEYl0a.jpg" },
      { brandName: "웰로리아", note: "포스파티딜세린 최대77%, 기억력 카피", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/healthcare/%EC%9B%B0%EB%A1%9C%EB%A6%AC%EC%95%84-146-thumb-ZjCAOxbzC5vTeLgA2tmPHFCqNVNQtb.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/healthcare/%EC%9B%B0%EB%A1%9C%EB%A6%AC%EC%95%84-146-full-9dUFXWfz7yP80X6KCSN5o1QgMsQlkT.jpg" },
    ] },
  'realestate': { name: "부동산", items: [] },
  'gaming': { name: "게임/엔터", items: [
      { brandName: "역발산", note: "게임 사전예약 D-1, 캐릭터 일러스트 배경", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/gaming/%EC%97%AD%EB%B0%9C%EC%82%B0-030-thumb-pnDs44XjL7mZh09z1nBk5O1ShF5ZrV.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/gaming/%EC%97%AD%EB%B0%9C%EC%82%B0-030-full-hbo5gywnZoTAl6K1rwEAO5FpVgzPeg.jpg" },
      { brandName: "세븐나이츠 리버스(넷마블)", note: "3주년 신캐릭터 등장, 게임 일러스트", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/gaming/%EC%84%B8%EB%B8%90%EB%82%98%EC%9D%B4%EC%B8%A0-%EB%A6%AC%EB%B2%84%EC%8A%A4-%EB%84%B7%EB%A7%88%EB%B8%94-113-thumb-X68zn3O96FCDllV8XmKkoZadFGlMjv.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/gaming/%EC%84%B8%EB%B8%90%EB%82%98%EC%9D%B4%EC%B8%A0-%EB%A6%AC%EB%B2%84%EC%8A%A4-%EB%84%B7%EB%A7%88%EB%B8%94-113-full-6XeEoNpB3o4R9HTPP5kK8jk8flNAn4.jpg" },
      { brandName: "옹진마켓", note: "보드게임 안주 과자 할인, 다품목 나열형", mimeType: "image/jpeg", thumbUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/food/%EC%98%B9%EC%A7%84%EB%A7%88%EC%BC%93-040-thumb-wCfgW1RmzJoIKsvHiI2Sg6EmSIfgYS.jpg", fullUrl: "https://oeiquwo26iglgctf.public.blob.vercel-storage.com/reference/food/%EC%98%B9%EC%A7%84%EB%A7%88%EC%BC%93-040-full-rahz8XMeggnUZZtYNlm0vAan5xwg2Q.jpg" },
    ] },
};

// 기획안 헬퍼의 "비주얼 레퍼런스 추천" 기능에서 사용 — 이미지가 1장 이상
// 있는 카테고리 목록(Gemini가 고를 수 있는 유효한 id만 프롬프트에 넣기 위함).
export function listNonEmptyCategories() {
  return Object.entries(REFERENCE_CATEGORIES)
    .filter(([, cat]) => cat.items.length > 0)
    .map(([id, cat]) => ({ id, name: cat.name }));
}

// 주어진 카테고리에서 최대 count장을 무작위로 골라 반환. 카테고리가
// 없거나 비어 있으면 빈 배열.
export function pickReferenceImages(categoryId, count) {
  const cat = REFERENCE_CATEGORIES[categoryId];
  if (!cat || !cat.items.length) return [];
  const shuffled = [...cat.items];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled.slice(0, count).map(({ brandName, note, thumbUrl, fullUrl }) => ({ brandName, note, thumbUrl, fullUrl }));
}
